# -*- coding: utf-8 -*-
"""Untitled77.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ppk-ugtfKONBoof552VIqTGJx2xUCnjr
"""

# 넘어짐 감지 (바로 이전에 측정된 x,y,z값과 현재 x,y,z각도의 변화량으로 감지하는 방식)
# 초기 기준값 (서 있는 상태에서 측정)
initial_angles = {'X': 0, 'Y': 5, 'Z': 85}  # 센서 몸에 달고 서있을 때의 기준값을 적어야 함 (임의의 값이므로 변경필요)
threshold_angle = 45  # Z축 임계값 (넘어짐으로 간주할 각도)
threshold_total_change = 50  # 총각도 변화량 임계값

# 가상 데이터 (센서에서 실시간으로 들어오는 값 <- 가상으로 만든 것이므로 실제 데이터 값으로 변경만 해주면 됨)
sensor_data = [
    {'X': 2, 'Y': 6, 'Z': 83},  # 정상 상태
    {'X': 10, 'Y': 15, 'Z': 70},  # 기울어진 상태
    {'X': 20, 'Y': 25, 'Z': 40},  # 넘어짐 상태
]

# 넘어짐 감지 알고리즘
previous_angles = initial_angles  # 초기 기준값으로 시작

for data in sensor_data:
    # 각도 보정
    corrected_angles = {
        axis: data[axis] - initial_angles[axis]
        for axis in data
    }

    # Z축 기준 넘어짐 감지
    if corrected_angles['Z'] < threshold_angle:
        print("Z축 기반: 넘어짐 가능성 감지!")

    # 3축의 총각도 변화량 계산
    total_change = sum(
        (data[axis] - previous_angles[axis])**2
        for axis in data
    )**0.5

    if total_change > threshold_total_change:
        print(f"3축 기반: 넘어짐 감지! 총각도 변화량: {total_change:.2f}")

    # 이전 상태 갱신
    previous_angles = data

    # 바로 이전 x,y,z값과 현재 x,y,z의 값을 비교하여 변화량을 측정하는 것이므로
    # 데이터를 받는 시간을 너무 짧게 하면 안될 것 같음
    #